# Eldritch Rose Miasma - wezterm
# place in ~/.config/wezterm/colors/, then: config.color_scheme = "Eldritch Rose Miasma"

[metadata]
name = "Eldritch Rose Miasma"
author = "Sam Lightbody"

[colors]
foreground = "#ebfafa"
background = "#0a140e"
cursor_bg = "#37f499"
cursor_fg = "#0a140e"
cursor_border = "#37f499"
selection_fg = "#e0def4"
selection_bg = "#384e42"
ansi = ["#222e28", "#eb6f92", "#37f499", "#e8be22", "#4d8bff", "#a48cf2", "#04d1f9", "#e0def4"]
brights = ["#6e6a86", "#f9515d", "#69f8b3", "#f1fc79", "#7aa6ff", "#fd92ce", "#66e4fd", "#ebfafa"]
