# Eldritch Rose Miasma - kitty
# include from kitty.conf:  include ./eldritch-rose.conf

background            #0a140e
foreground            #ebfafa
cursor                #37f499
cursor_text_color     #0a140e
selection_background  #384e42
selection_foreground  #e0def4
url_color             #a48cf2

active_border_color    #04d1f9
inactive_border_color  #222e28
active_tab_background   #0a140e
active_tab_foreground   #ebfafa
inactive_tab_background #0f1d16
inactive_tab_foreground #6e6a86

color0  #222e28
color8  #6e6a86
color1  #eb6f92
color9  #f9515d
color2  #37f499
color10 #69f8b3
color3  #e8be22
color11 #f1fc79
color4  #4d8bff
color12 #7aa6ff
color5  #a48cf2
color13 #fd92ce
color6  #04d1f9
color14 #66e4fd
color7  #e0def4
color15 #ebfafa
