# Eldritch Rose - tmux
# source this from tmux.conf: source-file ~/Projects/eldritch-rose/tmux/eldritch-rose.conf

set -g window-style 'bg=#1c1a26'
set -g window-active-style 'bg=#08161a'
set -g pane-border-style 'fg=#202e34'
set -g pane-active-border-style 'bold,fg=#04d1f9'
