# Eldritch Rose - tmux
# source this from tmux.conf: source-file ~/Projects/eldritch-rose/tmux/eldritch-rose.conf

set -g window-style 'bg=#15131e'
set -g window-active-style 'bg=#191724'
set -g pane-border-style 'fg=#26233a'
set -g pane-active-border-style 'bold,fg=#04d1f9'
