# Eldritch Rose Lifted - tmux
# source this from tmux.conf: source-file ~/Projects/eldritch-rose/tmux/eldritch-rose-lifted.conf

set -g window-style 'bg=#132d35'
set -g window-active-style 'bg=#0c2126'
set -g pane-border-style 'fg=#26363d'
set -g pane-active-border-style 'bold,fg=#04d1f9'
