# Eldritch Rose - foot
# include from foot.ini:  include=~/.config/foot/eldritch-rose.ini

[cursor]
color=191724 37f499

[colors]
background=191724
foreground=ebfafa
selection-foreground=e0def4
selection-background=403d52

regular0=26233a
regular1=eb6f92
regular2=37f499
regular3=f6c177
regular4=4d8bff
regular5=a48cf2
regular6=04d1f9
regular7=e0def4

bright0=6e6a86
bright1=f9515d
bright2=69f8b3
bright3=f1fc79
bright4=7aa6ff
bright5=fd92ce
bright6=66e4fd
bright7=ebfafa
